### ISSUE TITLE
Why are you using logit-normal sampling only for ImageNet experiment

### ISSUE THREAD

**Issue by Luciennnnnnn** [Alpha-VLLM/Lumina-T2X#62]
From the statements of your paper, logit-normal seems to be a general strategy to improve flow matching models training, why are you using logit-normal sampling only for ImageNet experiment?

**Comment by zhuole1025** [comment]
That's because we tested the lognorm schedule only at the very beginning of our T2I project and found no significant improvements. However, it is worth paying more attention to the schedule for training large-scale flow and diffusion models. FYI, there are some papers that propose new training schedules for flow models (https://arxiv.org/pdf/2405.20320)

**Comment by Luciennnnnnn** [comment]
Hi @zhuole1025 , thank your for the detailed explanation and paper recommendation! i'll take a look at the paper.
